on:
  push:
  schedule:
    - cron: '0 2 */15 * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build And Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        id: build_image
        run: |
          docker build -t yaoa/caddy-cloudflare:build -f ./Dockerfile .
          docker login -u $(dockerId) -p $(dockerPassword)
          export IMAGE_ID_TEMP=$(sudo docker images --filter=reference=yaoa/caddy-cloudflare:build --format "{{.ID}}")
          echo "##[set-output name=image_id;]$IMAGE_ID_TEMP"
      - name: Deploy Commit ID
        if: ${{ github.sha != '' }}
        env:
          commit_id: ${{ github.sha }}
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $(image_id) yaoa/caddy-cloudflare:$commit_id
          docker push yaoa/caddy-cloudflare:$commit_id
      - name: Deploy Latest
      - script: |
          docker tag $(image_id) yaoa/caddy-cloudflare:latest
          docker push yaoa/caddy-cloudflare:latest
        displayName: Deploy Latest
        condition: and(eq(variables['System.PullRequest.IsFork'], 'False'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
       
      - script: |
          docker tag $(image_id) yaoa/caddy-cloudflare:latest-develop
          docker push yaoa/caddy-cloudflare:latest-develop
        displayName: Deploy Develop
        condition: and(eq(variables['System.PullRequest.IsFork'], 'False'), eq(variables['Build.SourceBranch'], 'refs/heads/dev*'))
      - script: |
          docker tag $(image_id) yaoa/caddy-cloudflare:$BUILD_SOURCEBRANCHNAME
          docker push yaoa/caddy-cloudflare:$BUILD_SOURCEBRANCHNAME
        displayName: Deploy Branch
        condition: and(eq(variables['System.PullRequest.IsFork'], 'False'), startsWith(variables['Build.SourceBranch'], 'refs/heads/'))
      - script: |
          docker tag $(image_id) yaoa/caddy-cloudflare:$BUILD_SOURCEBRANCHNAME
          docker push yaoa/caddy-cloudflare:$BUILD_SOURCEBRANCHNAME
        displayName: Deploy Tag
        condition: and(eq(variables['System.PullRequest.IsFork'], 'False'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))